apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: dockerconfigjson-github-com
  labels:
    app: sample-fullstack-app
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJhbUZyZFdKaWREcG5hSEJmYVROTVNERllOVkJLVWpOV04yRjNNV1pLTlcxM1lrTktjM2QyUXpKc01XUmtXR0pJIn19fQ==