name: Main

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published

env:
  FRONTEND_PROJECT_NAME: sample-app-frontend
  BACKEND_PROJECT_NAME: sample-app-backend
  ORGANIZATION: jakubbt

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        cd ./backend
        npm install
  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: |
        cd ./frontend
        npm install
    - name: build
      run: |
        cd ./frontend
        npm run build
  push_version_backend:
    name: Push backend container
    runs-on: ubuntu-latest
    needs: backend
    steps:

    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build container image
      run: |
        cd ./backend
        docker build -t ${{ env.ORGANIZATION }}/${{ env.BACKEND_PROJECT_NAME }} .

    - name: Push image to ghcr
      run: |
        docker tag ${{ env.ORGANIZATION }}/${{ env.BACKEND_PROJECT_NAME }} ghcr.io/$ORGANIZATION/${{ env.BACKEND_PROJECT_NAME }}:latest
        
        docker push ghcr.io/${{ env.ORGANIZATION }}/${{ env.BACKEND_PROJECT_NAME }}:latest

  push_version_frontend:
    name: Push frontend container
    runs-on: ubuntu-latest
    needs: frontend
    steps:

    - uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}

    - name: Build container image
      run: |
        cd ./frontend
        docker build -t ${{ env.ORGANIZATION }}/${{ env.FRONTEND_PROJECT_NAME }} .

    - name: Push image to ghcr
      run: |
        docker tag ${{ env.ORGANIZATION }}/${{ env.FRONTEND_PROJECT_NAME }} ghcr.io/$ORGANIZATION/${{ env.FRONTEND_PROJECT_NAME }}:latest
        
        docker push ghcr.io/${{ env.ORGANIZATION }}/${{ env.FRONTEND_PROJECT_NAME }}:latest
